name: Github Actions Demo
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start test 🧪"
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test
      - run: npm run test-coverage